---
# tasks file for hdp-deploy-certs

- name: print {{ service }} variables
  debug: msg={{ ranger_services[service] }}

- name: delete certfiles
  file: path={{ ranger_services[service].keystore_path }} state=absent
- file: path={{ ranger_services[service].truststore_path }} state=absent

- name: deploy key for service
  copy: src=./ssl_certs/{{ ranger_services[service].cert_filename }} dest=/tmp/

- name: deploy admin trust file
  copy: src=./ssl_certs/{{ ranger_admin_keystore.cert_filename }} dest=/tmp/

- name: import ranger trust to truststore
  shell: keytool -import -file /tmp/{{ ranger_admin_keystore.cert_filename }} -alias "{{ ranger_admin_keystore.alias }}" -keystore "{{ ranger_services[service].truststore_path }}" -storepass "{{ ranger_services[service].password }}" -noprompt

- name: import key to keystore
  shell: keytool -import -file /tmp/{{ ranger_services[service].cert_filename }} -alias "{{ ranger_services[service].alias }}" -keystore "{{ ranger_services[service].keystore_path }}" -storepass "{{ ranger_services[service].password }}" -noprompt

- name: delete cert files
  file: path=./tmp/{{ ranger_admin_keystore.cert_filename }} state=absent
- file: path=./tmp/{{ ranger_services[service].cert_filename }} state=absent
